import fs from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { config } from '../config.js';
import { exportTree } from './markdown.js';
import { getSection, publicBase } from './integrations.js';

/**
 * Mirrors all pages as Markdown into a Git repository (one commit per sync, only when something changed).
 * The wiki is the source of truth: the remote branch's content is replaced, its history is kept.
 * HTTPS remotes with a token in the URL work out of the box (https://user:token@host/org/repo.git).
 */
const run = promisify(execFile);
const repoDir = path.join(config.dataDir, 'git', 'repo');

export const gitState = { running: false, lastRun: null, lastOk: null, lastCommit: null, lastError: null, log: [] };

const redact = (s, url) => {
  let out = String(s || '');
  if (url) out = out.replaceAll(url, '<remote>');
  return out.replace(/\/\/[^/@\s]+@/g, '//***@');
};

async function git(args, url, opts = {}) {
  try {
    const { stdout } = await run('git', args, {
      cwd: repoDir,
      timeout: 120000,
      maxBuffer: 10 * 1024 * 1024,
      env: { ...process.env, GIT_TERMINAL_PROMPT: '0', GIT_ASKPASS: 'echo', LC_ALL: 'C' },
      ...opts,
    });
    return stdout.trim();
  } catch (err) {
    throw new Error(redact(err.stderr || err.message, url).trim().split('\n').slice(-3).join(' '));
  }
}

export async function gitAvailable() {
  try {
    await run('git', ['--version'], { timeout: 5000 });
    return true;
  } catch {
    return false;
  }
}

export async function syncGit({ force = false } = {}) {
  const cfg = await getSection('git');
  if (!cfg.remote) throw new Error('Kein Git-Remote eingerichtet');
  if (!force && !cfg.enabled) return null;
  const url = cfg.remote;
  // only real transports – no ext::/fd:: helpers, no option injection
  if (!/^(https?:\/\/|ssh:\/\/|git@[\w.-]+:|\/)/.test(url)) throw new Error('Ungültige Repository-URL (https://, ssh://, git@host: oder absoluter Pfad)');
  if (gitState.running) throw new Error('Synchronisierung läuft bereits');
  gitState.running = true;
  gitState.lastRun = new Date().toISOString();
  const branch = (cfg.branch || 'main').replace(/[^\w./-]/g, '') || 'main';
  const note = (m) => gitState.log.unshift({ at: new Date().toISOString(), message: m }) && gitState.log.splice(20);
  try {
    await fs.mkdir(repoDir, { recursive: true });
    if (!existsSync(path.join(repoDir, '.git'))) {
      await git(['init', '-q', '-b', branch], url);
      await git(['remote', 'add', 'origin', url], url);
    } else {
      await git(['remote', 'set-url', 'origin', url], url);
    }
    await git(['config', 'user.name', cfg.authorName || 'Bastion'], url);
    await git(['config', 'user.email', cfg.authorEmail || 'bastion@localhost'], url);

    // start from the remote branch if it exists (keeps history, allows fast-forward pushes)
    const remoteHas = await git(['ls-remote', '--heads', 'origin', branch], url);
    if (remoteHas) {
      await git(['fetch', '-q', '--depth', '50', 'origin', branch], url);
      await git(['checkout', '-q', '-B', branch, 'FETCH_HEAD'], url);
    } else {
      await git(['checkout', '-q', '-B', branch], url).catch(() => {});
    }
    for (const entry of await fs.readdir(repoDir)) {
      if (entry !== '.git') await fs.rm(path.join(repoDir, entry), { recursive: true, force: true });
    }
    const files = await exportTree(repoDir, { baseUrl: await publicBase() });
    await fs.writeFile(path.join(repoDir, 'README.md'), `# Wiki export\n\nAutomatically generated by Bastion – ${files} pages. Changes here are overwritten on the next sync.\n`);
    await git(['add', '-A'], url);
    const status = await git(['status', '--porcelain'], url);
    if (!status) {
      note('Keine Änderungen');
      gitState.lastOk = new Date().toISOString();
      gitState.lastError = null;
      return { changed: false };
    }
    const changed = status.split('\n').length;
    await git(['commit', '-q', '-m', `Wiki-Export: ${changed} Datei(en) geändert`], url);
    await git(['push', '-q', 'origin', `HEAD:refs/heads/${branch}`], url);
    gitState.lastCommit = await git(['rev-parse', '--short', 'HEAD'], url);
    gitState.lastOk = new Date().toISOString();
    gitState.lastError = null;
    note(`${changed} Datei(en) übertragen (${gitState.lastCommit})`);
    return { changed: true, files: changed, commit: gitState.lastCommit };
  } catch (err) {
    gitState.lastError = err.message;
    note(`Fehler: ${err.message}`);
    throw err;
  } finally {
    gitState.running = false;
  }
}
